# Generated by Django 3.2.7 on 2021-09-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210914_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kakao_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
