# Generated by Django 3.2.7 on 2021-09-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_signup_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signup_type',
            field=models.CharField(choices=[(1, 'Flix'), (2, 'Kakao'), (3, 'Google')], default=1, max_length=10),
        ),
    ]
