# Generated by Django 3.2.7 on 2021-09-14 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=400)),
                ('nation', models.CharField(max_length=45)),
                ('thumb_nail', models.URLField(max_length=300)),
            ],
            options={
                'db_table': 'contents',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=400)),
                ('running_time', models.TimeField()),
                ('thumb_nail', models.URLField(max_length=300)),
                ('file', models.URLField(max_length=300)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='contents.content')),
            ],
            options={
                'db_table': 'details',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='contents', to='contents.Genre'),
        ),
    ]
