# Generated by Django 3.2.7 on 2021-09-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20210914_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='running_time',
            field=models.IntegerField(),
        ),
    ]
