# Generated by Django 3.2.7 on 2021-09-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_detail_running_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='episode',
            field=models.CharField(max_length=100),
        ),
    ]
