# Generated by Django 3.2.7 on 2021-09-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='like',
            field=models.BooleanField(default=True),
        ),
    ]
